# Dubbo Invoke 配置文件

registry:
  # 注册中心地址
  address: zookeeper://127.0.0.1:2181
  # 注册中心协议
  protocol: zookeeper
  # 连接超时时间
  timeout: 5s
  # 认证信息（可选）
  username: ""
  password: ""

application:
  # 应用名称
  name: dubbo-invoke-cli
  # 应用版本
  version: 1.0.0

defaults:
  # 默认调用超时时间
  timeout: 3s
  # 默认协议
  protocol: dubbo
  # 默认版本（可选）
  version: ""
  # 默认分组（可选）
  group: ""