application:
    name: dubbo-invoke-client
    owner: ""
    version: 1.0.0
consumer:
    generic: true
    loadbalance: random
    retries: 0
    timeout: 3s
protocol:
    name: dubbo
    port: 20880
registry:
    address: zookeeper://127.0.0.1:2181
    password: ""
    timeout: 5s
    username: ""
